load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["docker.go"],
    visibility = ["//lib:__subpackages__"],
    deps = ["//lib/internal/types:go_default_library"],
)
